Repository CA-G12/team9-QuizApp, pull requests merged in 2022-07, with the labels that each got.

#6 linking pages and add font-family to all pages
  css/question.css
  css/result.css
  css/style.css
  html/question.html
  html/result.html
  index.html
Labels: waiting-reviwe

#7 2 create landing page
  css/style.css
  images/quiz Logo.PNG
  index.html
Labels: waiting-reviwe

#8 create and style questions page
  css/question.css
  html/question.html
Labels: awating-review

#9 create and style result
  css/result.css
  html/result.html
  images/Capture.JPG
Labels: awating-review

#11 edit the link of files
  html/question.html
  html/result.html
  index.html
Labels: awating-review

#13 add js folder and add link to js file
  html/question.html
  html/result.html
  index.html
  js/main.js
  js/question.js
  js/result.js
Labels: awating-review

#15 create js file for question page
  js/question.js
Labels: awating-review

#17 improvment qusetion page and fixing some cases
  css/question.css
  html/question.html
  js/question.js
Labels: approved

#20 create function in main.js 'set users in localstorge' and add create …
  css/style.css
  index.html
  js/main.js
  js/question.js
Labels: awating-review

#21 write a function that display the results of scores
  html/result.html
  js/main.js
  js/result.js
Labels: approved
